version: '3.4'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile

  shoppingcarddb:
    image: redis:alpine

  catalogdb:
    image: mongo
   
  shoppingcard.api:
    image: ${DOCKER_REGISTRY-}shoppingcardapi
    build:
      context: .
      dockerfile: src/Services/ShopppingCard/ShoppingCard.API/Dockerfile

  

volumes:
  mongo_data:


